version: '3'
services: 
  dms:
    image: naushada/onprem:1.0
    ports: 
      - 192.168.0.133:58080:58080
      - 58989:58989
    command:
      - /opt/xAPP/uniimage/uniimage
      - --web-port 58080
      - --server-port 58989
      - --protocol tcp
      - --role server
      - --timeout 1000
      - --mongodb-uri mongodb://onprem:onprem123@192.168.0.133/onprem?maxPoolSize=50
  dmc:
    image: naushada/onprem:1.0
    command:
      - /opt/xAPP/uniimage/uniimage
      - --server-ip 192.168.0.133
      - --server-port 58989
      - --protocol tcp
      - --role client
      - --timeout 1000
      - --userid test
      - --password test123
    